title: Portfolio
description: Portfolio de Grandpere
#theme: minima

collections:
  experiences:
    output: false
    sort_by: order
  projects:
    output: false
    sort_by: order
  cv:
    output: false

include:
  - _pages
